FROM python:3.7-alpine

RUN apk add --no-cache gcc musl-dev linux-headers mariadb-dev mariadb-client

WORKDIR /code

ENV FLASK_APP=ChatGebetaMsg
ENV FLASK_RUN_HOST=0.0.0.0


COPY requirements.txt requirements.txt

RUN /usr/local/bin/python -m pip install --upgrade pip
# RUN pip install mysqlclient
RUN pip install -r requirements.txt


EXPOSE 5000

COPY . .

RUN pip install -e . 

CMD ["flask", "run" ,"--debug"]