name: model-service CI

on:
  push:
    branches: ['main']
    paths:
      - model-service/**
  pull_request:
    branches: ['main']
    paths:
      - model-service/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker compose -f model-service/docker-compose.yml up -d
        