name: msg-service CI

on:
  push:
    branches: ['main']
    paths:
      - msg-service/**
  pull_request:
    branches: ['main']
    paths:
      - msg-service/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        uses: '../actions/service-build.yml'
        with:
          service-name: 'msg-service'
      - name: Run the Docker image
        uses: '../actions/service-run.yml'
        with:
          service-name: 'msg-service'
