name: msg-service CI

on:
  push:
    branches: ['main']
    # paths:
    #   - msg-service/**
  pull_request:
    branches: ['main']
    paths:
      - msg-service/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build the Docker image
        uses: actions/checkout@v3
        uses: ./actions/service-build
        with:
          service-name: 'msg-service'
      - name: Run the Docker image
        uses: actions/checkout@v3
        uses: ./actions/service-run
        with:
          service-name: 'msg-service'
